package com.example.miniprojet_oussema_jedidi.entities;

import java.util.ArrayList;


import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import lombok.Data;

/**
 * Interventions generated by hbm2java
 */
@Entity
@Data
public class Interventions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2915440570717351816L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private String titre;
	private Date datedebut;
	private Date datefin;
	private Date heuredebutplan;
	private Date heurefinplan;
	private String commentaires;
	private Date dateplanification;
	private Date heuredebuteffect;
	private Date heurefineffect;
	private boolean terminee;
	private Date dateterminaison;
	private boolean validee;
	private Date datevalidation;
	
	@ManyToOne()
	@JoinColumn(name = "priorite_id",nullable = false)
	private Priorites priorites;
	
	@OneToMany(mappedBy = "interventions")
	private List<Images> imagesList = new ArrayList<Images>();
	
	@ManyToOne()
	@JoinColumn(name="site_id")
	private Sites sites;
	
	@OneToMany(mappedBy = "intervention")
	private List<Taches> tachesList = new ArrayList<Taches>();
	
	@ManyToMany(mappedBy = "interventionsList" )
	private List<Employes> employesList = new ArrayList<Employes>();
	
	
	private int valsync;

	public Interventions() {
	}

	



}
